### ISSUE TITLE
Errore quando uso il comando /cicero

### ISSUE THREAD

**Issue by goldr31** [ForgottenWorld/FWCicero#1]
Versione di minecraft:
1.15.2

Versione di Paper:
Git paper 333

Cosa mi aspetto:
quando metto il comando cicero vengo teletrasportato in una delle città.

Cosa accade:

> > 03.06 19:05:36 [Server] INFO goldr31 issued server command: /cicero
> > 03.06 19:05:36 [Server] ERROR null
> > 03.06 19:05:36 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'cicero' in plugin FWCicero v1.0.0-SNAPSHOT
> > 03.06 19:05:36 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.2.jar:git-Paper-333]
> > 03.06 19:05:36 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-333]
> > 03.06 19:05:36 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761) ~[patched_1.15.2.jar:git-Paper-333]
> > 03.06 19:05:36 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1860) ~[patched_1.15.2.jar:git-Paper-333]
> > 03.06 19:05:36 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1668) ~[patched_1.15.2.jar:git-Paper-333]
> > 03.06 19:05:36 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-333]
> > 03.06 19:05:36 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-333]
> > 03.06 19:05:36 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-333]
> > 03.06 19:05:36 [Server] INFO at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-333]
> > 03.06 19:05:36 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-333]
> > 03.06 19:05:36 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-333]
> > 03.06 19:05:36 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-333]
> > 03.06 19:05:36 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1097) ~[patched_1.15.2.jar:git-Paper-333]
> > 03.06 19:05:36 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1090) ~[patched_1.15.2.jar:git-Paper-333]
> > 03.06 19:05:36 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-333]
> > 03.06 19:05:36 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1051) ~[patched_1.15.2.jar:git-Paper-333]
> > 03.06 19:05:36 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:966) ~[patched_1.15.2.jar:git-Paper-333]
> > 03.06 19:05:36 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
> > 03.06 19:05:36 [Server] INFO Caused by: java.lang.IllegalArgumentException: location
> > 03.06 19:05:36 [Server] INFO at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.15.2.jar:git-Paper-333]
> > 03.06 19:05:36 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.entity.CraftPlayer.teleport(CraftPlayer.java:744) ~[patched_1.15.2.jar:git-Paper-333]
> > 03.06 19:05:36 [Server] INFO at it.forgottenworld.fwcicero.command.CiceroCommandExecutor.teleportAction(CiceroCommandExecutor.java:304) ~[?:?]
> > 03.06 19:05:36 [Server] INFO at it.forgottenworld.fwcicero.command.CiceroCommandExecutor.onCommand(CiceroCommandExecutor.java:64) ~[?:?]
> > 03.06 19:05:36 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-333]
> > 03.06 19:05:36 [Server] INFO ... 17 more

**Comment by Markus27** [comment]
Ciao @goldr31,
ho indagato sul problema, consiste nel fatto che una delle città salvate nel Cicero non esiste più. 
Il controllo dell'evento del disband delle town e la rimozione della stessa dall'elenco verrà introdotta con una delle prossime versioni.
Grazie per aver segnalato il problema.

**Comment by Markus27** [comment]
Risolto d3fad16fb744e538a36d65a23b9f0cdf975f5d05
