### ISSUE TITLE
Il plugin non funziona un cazzo

### ISSUE THREAD

**Issue by SirVecchio** [ForgottenWorld/FWCicero#2]
Il plugin nonostante mi vengano dati i permessi non funziona 
Sono in grado di fare /cicero add NOMECITTà
Non sono in grado di fare /cicero 
Non sono in grado di fare /cicero timeleft

[20:405 INFO]: SirVecchio issued server command: /cicero
[20:40:10 INFO]: SirVecchio issued server command: /cicero add PippoBaudo

**Comment by SirVecchio** [comment]
Risolto mi sono inserito nella whitelist di cicero

**Comment by Markus27** [comment]
Si esatto il plugin funziona con i nuovi utenti non con quelli già presenti o che hanno già eseguito i comandi in precedenza, per poter essere re inseriti nella whitelist bisogna fare il comando `/cicero allow <Player>`.

**Comment by SirVecchio** [comment]
Che sarà un altro giro di tutte le città e basta vero? (Almeno così era nei test)

**Comment by Markus27** [comment]
Il comando `/cicero allow <Player>` permette ad un player di ricominciare il giro delle città da capo con scadenza dopo il tempo prestabilito, in questo caso 2 giorni. In pratica riattiva ad un player vecchio tutti i privilegi di un player nuovo.

**Comment by SirVecchio** [comment]
Sono soddisfatto per questa issue
